### ISSUE TITLE
Metadaten-Editor: Datensatz (in Gänze) kopieren und einfügen

### ISSUE THREAD

**Issue by yannic-bruegger** [lucascranach/cranach-metadata-service#1]
Gunnar:

Gern hätte ich die Möglichkeit, den gesamten Datensatz zu kopieren, um den Eintrag bei einem nächsten Bild in die Maske wieder einzufügen - und ggf. weiter zu bearbeiten (Es gibt z.B. einige Detailfotos, die alle die gleiche Beschreibung erhalten).

**Comment by CranacharchivGunnar** [comment]
Danke, um das Tool nutzen zu können, ist der Punkt auch wichtig. Ansonsten braucht es viel, viel Zeit und wir hatten die Kopierfunktion auch in dem alten Tool.

**Comment by yannic-bruegger** [comment]
Kopierfunktion habe ich mal implementiert - leider stoßen wir auf ein paar technische Schwierigkeiten. Für Chrome funktioniert es jetzt. Das sieht alles noch nicht gut aus, ist aber ein erster Ansatz zum Testen. Für Firerfox muss ich noch einmal prüfen, ob es überhaupt möglich ist.

![Image](https://github.com/lucascranach/cranach-metadata-service/assets/36576062/0f014f63-2f72-4b92-8ada-4d1344807267)

**Comment by CranacharchivGunnar** [comment]
Hi Yannic, 
das funktioniert gut. Wenn ich weiß, dass es nur in Chrome geht, reicht mir das .
So kann ich jetzt z.B. bei 10 Detailaufnahmen zu einem Bild mit jeweils 6 Klicks, d.h. 60 Klicks die Angaben füllen. Zuvor war das ein Vielfaches.
Vorschlag: Bei Öffnung des Editors kann m.E. gleich die gefüllte oder wenn keine Daten vorhanden, gleich die leere Eingabemaske angezeigt werden. Nicht erst der Hinweis "Create new Metadata Entry". Das würde mir bei Bildern mit gleicher Beschriftung die Anzahl der Klicks pro Bild von 6 auf 5 reduzieren. 
Frage: Wie ist das Procedere bis zur Sichtbarkeit? Ich sehe jetzt im internen und im öffentlichen Bereich einige Bildbeschriftungen, die ich zuerst getätigt habe. Andere, die die ich zwischenzeitlich noch ergänzt habe, werden mir noch nicht angezeigt. Darauf hattest Du hingewiesen, doch wer muss was machen, bzw. wen benachrichtige ich und wie viel Zeit kostet Euch das Freischalten?

**Comment by yannic-bruegger** [comment]
Hi Gunnar, das freut mich sehr! An firefox setze ich mich gerade trotzdem noch einmal dran. Ist besser, wenn es überall funktioniert auch für die Wartbarkeit des Systems.
 
Den Button würde ich aus technischen Gründen gerne erstmal so lassen, wie es jetzt ist. Technische steckt da folgendes hinter:
- Wird der Button angezeigt, existiert **keine** entsprechende Metadaten-Datei
- Wird ein leeres Formular angezeigt, existiert **eine leere** Metadaten-Datei

Weil in diesen beiden Fällen einiges an Fehlerpotential steckt, würde ich es gerne so belassen. So haben wir einen etwas tieferen Einblick in die hinterliegenden Dateien. Wenn es dann bald solide funktioniert, können wir deinen Vorschlag aber gerne implementieren.

Sichtbar werden deine Änderungen bei der nächsten Veröffentlichung des Programms "Cranach Artefacts". Das kann potentiell jeder von uns. Es ist momentan noch etwas aufwendig aber ich entwickel gerade ein Script, sodass jeder von uns das innerhalb von wenigen Sekunden kann. :) Kommt hoffentlich auch heute noch.

**Comment by yannic-bruegger** [comment]
Firefox-Support ist jetzt drin

**Comment by CranacharchivGunnar** [comment]
Super, teste ich später...
